### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by shshaw**
Rewrite to simplify and make loudlinks more customizable
- `data-sound` instead of `data-src` attribute for clarity
- Absolute URL support with `{{type}}` placeholder
- Simplified and combined functions where necessary
- Added the ability to run `loudlinks();` later to support dynamically added items.

### CODE REVIEW

**Comment by MahdiF** [comment]
Thanks a MILLION Shaw.
I've learned a lot of things from your code, I really appreciate it.

**Comment by shshaw** [comment]
No problem! Thanks for merging. If you have any questions, let me know. I
tried to comment the code, but I'm happy to explain the changes.

**Comment by MahdiF** [comment]
Oh thanks again, yeah I saw the comments, I just don't understand how
regular expressions work, need to read a lot about it.
I loved that you added the possibility to add a sound file in any folder,
was going to add that by myself.

Now I'll have to think of a way to preload all the sounds to make it work
faster.

Thanks again Shaw.

**Comment by shshaw** [comment]
Regarding regular expressions, the one I used is very basic! Might help introduce you to regular expressions since there isn't any funny business going on:

`/{{type}}/gi` 
The `/` indicates that this is a regular expression, and marks the start and end of the phrase to search for.
The `{{type}}` is literally searching for the phrase `{{type}}` to be replaced in the URL. 
The `gi` are RegEx flags, `g` means a global search (won't stop after the first match) and `i` means case-insensitive, so `{{TYPE}}`, `{{type}}`, and `{{TyPe}}` all match.

As for preloading, the first method off the top of my head would be on initialization to create an `<audio>` element for each sound, set the sources, add the `preload` attribute, then link all the events for that source to that audio element. That way the browser has a chance to preload all the audio files before triggered.

Some rough pseudo code:

```
var elements = {};

for (i = 0; i < hoverLength; i++) { 
  var src = getSource(hoverLinks[i]);
  if ( ! elements[src] ) { // if the element for this src hasn't been created yet, let's create it now.
    elements[src] = document.createElement('audio');
    // add preload attribute & sources to new element...
  }
  trackHover(hoverLinks[i],elements[src]); // Set up hover events, but now it has a second parameter for the <audio> element to trigger.

}
```

**Comment by MahdiF** [comment]
Whoa man! Thanks a lot for explaining the regular expressions you've used.

As for the preloading the audio, yeah I thought of doing the same, but I'm
just afraid that'll affect the page speed if you have a bunch of links in
the page, or you think it won't?

**Comment by shshaw** [comment]
Depends on the quantity of elements created and the size of the files.
Since the JS file should be run from the footer (right before the </body>
tag), it should not affect the visible page load since the audio files
won't start downloading until after the page has rendered. People on
limited connections may not appreciate the extra downloads, and if you're
loading/creating a bunch of audio it may affect performance.

I'd say if the target is 1-15 unique sounds, then file size and performance
would not be a concern in most cases.

**Comment by MahdiF** [comment]
Also mobile users won't appreciate the big download.

I'll work on adding it as an option so people can choose to use it or not.

**Comment by shshaw** [comment]
Maybe like this: `<a href="#" data-sound="/sounds/beep.{{type}}" data-ll-preload="true">`, then on initialization it can check if the `data-ll-preload` attribute is set, and if so, create a new `<audio>` element for that particular sound. LoudLinks can keep an object containing the elements like in my example above, and attach events based on if it's a preloaded element or not.

**Pull request merged**
